version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: server
    working_dir: /app
    env_file:
      - ./frontend/.env
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
      - ./backend/uploads:/app/uploads
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data_dev:

networks:
  app-network:
